# O Blueprint do Render organiza múltiplos serviços (Full Stack) usando um único arquivo.
services:

  # ===========================================================================
  # 1. SERVIÇO: FRONTEND DO CLIENTE (Site Estático React/Vite)
  # ===========================================================================
  - type: web # Define como serviço web
    env: static # Especifica que o ambiente é estático (HTML/JS/CSS do Vite)
    name: citybank-cliente # Nome único no painel do Render
    rootDir: frontend-cliente # Pasta no seu Git onde está este frontend
    buildCommand: npm ci && npm run build # Instala dependências e gera a build de produção
    staticPublishPath: dist # Pasta gerada pelo Vite para publicação
    routes:
      - type: rewrite # Configuração para evitar Erro 404 no React Router
        source: /*
        destination: /index.html 
    envVars:
      - key: VITE_API_BASE_URL 
        value: https://citybank-api.onrender.com/api # URL da sua API Java

  # ===========================================================================
  # 2. SERVIÇO: FRONTEND DO ADMINISTRADOR (Painel Gerencial Estático)
  # ===========================================================================
  - type: web # Define como serviço web
    env: static # Especifica que o ambiente é estático
    name: citybank-admin 
    rootDir: frontend-admin # Pasta no seu Git onde está o admin
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite 
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://citybank-api.onrender.com/api

  # ===========================================================================
  # 3. SERVIÇO: BACKEND (API RESTful Java com Spring Boot)
  # ===========================================================================
  - type: web # Tipo 'web' para aplicação servidora contínua (Java)
    name: citybank-api 
    runtime: java # Ambiente nativo Java
    plan: free 
    rootDir: backend # Pasta no Git onde está a API Java
    buildCommand: ./mvnw clean package -DskipTests # Compila e gera o .jar
    startCommand: java -jar target/bank-api-0.0.1-SNAPSHOT.jar # Inicia a aplicação
    envVars:
      - key: SERVER_PORT 
        value: 10000 
      
      # PROPRIEDADES DE SEGURANÇA (Configuradas manualmente no painel do Render)
      - key: JWT_SECRET 
        sync: false 
      - key: SPRING_DATASOURCE_URL 
        sync: false 
      - key: SPRING_DATASOURCE_USERNAME 
        sync: false 
      - key: SPRING_DATASOURCE_PASSWORD 
        sync: false